spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news?characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
      database: MySQL
      show-sql: true
      hibernate:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

